name: Test Blender location using Node.js

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        blender-version: [3.5.0]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
      
    - name: Install dependencies
      run: npm i

    - name: Download and install Blender
      run: |
        if [ "${{ matrix.os }}" = "macos-latest" ]; then
          curl -L "https://ftp.halifax.rwth-aachen.de/blender/release/Blender3.5/blender-3.5.0-macos-x64.dmg" -o blender.dmg
          hdiutil attach blender.dmg
          cp -R /Volumes/Blender/Blender.app /Applications/
          hdiutil detach /Volumes/Blender/
        else
          apt-get install blender
        fi

    - name: Test
      run: npm test
