name: Test Blender location using Node.js

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        blender-version: [3.5.0]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
      
    - name: Install dependencies
      run: npm i

    - name: Download and install Blender
      run: |
        if [ "${{ matrix.os }}" = "macos-latest" ]; then
          curl -L "https://www.blender.org/download/release/Blender3.5/blender-3.5.0-macos-x64.dmg" -o blender.dmg
          hdiutil attach blender.dmg
          cp -R /Volumes/Blender/Blender.app /Applications/
          hdiutil detach /Volumes/Blender/
        elif [ "${{ matrix.os }}" = "windows-latest" ]; then
          curl -L "https://www.blender.org/download/release/Blender3.5/blender-3.5.0-windows-x64.msi" -o blender.msi
          msiexec /i blender.msi /quiet
        else
          curl -L "https://www.blender.org/download/release/Blender3.5/blender-3.5.0-linux-x64.tar.xz" -o blender.tar.xz
          tar xf blender.tar.xz
          sudo mv blender-* /opt/blender
        fi

    - name: Test
      run: npm test
